# Rime 简化配置 - 专注拼音词库优化
# encoding: utf-8

config_version: '0.40'

# 万象词库 + 简体中文拼音
schema_list:
  - schema: wanxiang
  - schema: luna_pinyin_simp

# 候选词显示设置 - 8个候选字
menu:
  page_size: 8

# 保持简单的切换方式
switcher:
  caption: 〔输入方案〕
  hotkeys:
    - Control+grave
  save_options:
    - ascii_punct
  fold_options: true
  abbreviate_options: true

# 按键绑定 - 标准翻页键
key_binder:
  bindings:
    __patch:
      - key_bindings:/emacs_editing
      - key_bindings:/move_by_word_with_tab
      - key_bindings:/paging_with_minus_equal
      - key_bindings:/paging_with_comma_period

# 识别模式 - 斜杠直接输出
recognizer:
  import_preset: default
  patterns:
    email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
    url: "^(www[.]|https?://|ftp[.]|mailto:|file:///)[^ ]*$"
    slash: "^/[^ ]*$"

# 斜杠处理器 - 直接输出斜杠
punctuator:
  import_preset: default
  half_shape:
    "/": "/"

# ASCII模式设置 - Shift直接输入英文
ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Shift_L: inline_ascii
    Shift_R: inline_ascii
    Caps_Lock: clear