# Rime 简化配置 - 专注拼音词库优化
# encoding: utf-8

config_version: '0.40'

# 万象词库 + 简体中文拼音
schema_list:
  - schema: wanxiang
  - schema: luna_pinyin_simp

# 候选词显示设置 - 增加数量提高准确率
menu:
  page_size: 10

# 保持简单的切换方式
switcher:
  caption: 〔输入方案〕
  hotkeys:
    - Control+grave
  save_options:
    - ascii_punct
  fold_options: true
  abbreviate_options: true

# 保持默认按键绑定
key_binder:
  bindings:
    - { when: has_menu, accept: Tab, send: Down }
    - { when: has_menu, accept: Shift+Tab, send: Up }

# 识别模式保持简单
recognizer:
  import_preset: default
  patterns:
    email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
    url: "^(www[.]|https?://|ftp[.]|mailto:|file:///)[^ ]*$"

# ASCII模式设置
ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Shift_L: inline_ascii
    Shift_R: commit_text
    Caps_Lock: clear