# wanxiang.custom.yaml - 万象拼音优化配置

patch:
  # 1. 候选词数量设为9个
  menu/page_size: 9
  
  # 2. 启用用户词典和自动调频
  translator/enable_user_dict: true
  translator/enable_sentence: true
  translator/enable_completion: true
  translator/initial_quality: 1.2
  
  # 3. 配置Shift键 - 直接输入英文不提交候选词
  ascii_composer:
    good_old_caps_lock: true
    switch_key:
      Shift_L: inline_ascii
      Shift_R: inline_ascii
      Caps_Lock: clear
      
  # 4. 按键绑定 - 添加翻页键和其他优化
  key_binder/bindings:
    __patch:
      - key_bindings:/emacs_editing
      - key_bindings:/move_by_word_with_tab  
      - key_bindings:/paging_with_minus_equal
      - key_bindings:/paging_with_comma_period
      
  # 5. 翻译器配置
  engine/translators:
    - punct_translator  
    - script_translator
    
  # 6. 标点符号配置 - 确保中文标点正确
  punctuator:
    import_preset: symbols
    half_shape:
      ",": "，"
      ".": "。"
      "?": "？"
      "!": "！"  
      ";": "；"
      ":": "："
      "\\": "、"
      "/": "/"
      
  # 7. 识别器配置 - 优化各种模式
  recognizer/patterns:
    email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
    url: "^(www[.]|https?://|ftp[.]|mailto:|file:///)[^ ]*$"
    reverse_lookup: "`[a-z]*'?$"
    
  # 8. 开关状态设置
  switches:
    - name: ascii_mode
      reset: 0
      states: [ 中文, 西文 ]
    - name: full_shape
      reset: 0  
      states: [ 半角, 全角 ]
    - name: simplification
      reset: 1
      states: [ 漢字, 汉字 ]
    - name: ascii_punct
      reset: 0
      states: [ 。，, ．， ]
