# wanxiang.custom.yaml - 万象拼音优化配置

patch:
  # 1. 设置输入方案为全拼
  speller/algebra:
    __patch:
      - wanxiang.schema:/全拼
      
  # 2. 候选词数量设为8个
  menu/page_size: 8
  
  # 3. 启用用户词典
  translator/enable_user_dict: true
  
  # 4. 启用整句输入
  translator/enable_sentence: true
  
  # 5. 配置Shift键切换中英文
  ascii_composer:
    good_old_caps_lock: true
    switch_key:
      Shift_L: inline_ascii
      Shift_R: commit_text